server:
  applicationConnectors:
    - type: http
      port: 25010
  adminConnectors:
    - type: http
      port: 25011
message: Hi %s!, now you will learn about %s from Stack Abuse!
firstParameter: Friend
secondParameter: Dropwizard
